server:
  port: 80

spring:
  application:
    name: webserver-gateway
  devtools:
    restart:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.102:8848
        fail-fast: true
        enabled: false
    gateway:
      enabled: true
      routes:
      #????,id?????????
      - id: qkl-auth
        uri: http://localhost:8080
        #????????????????uri?
        predicates:
          - Path=/api/user/**